Repository WeonTrip-WonT/WonT, pull requests merged in 2024-02, with the labels that each got.

#10 Design/Detail : MyPage 마크업 및 스타일링
  .eslintrc.json
  .prettierrc
  .prettuerrc
  .prettuerrc.json
  pnpm-lock.yaml
  postcss.config.js
  public/detailpage/detailPlaceDefault.jpg
  public/mypage/myPlanDefaultImage.jpg
  public/mypage/myReviewDefaultImage-1.jpg
  public/mypage/myReviewDefaultImage-2.jpg
  public/svg/apple-login.svg
  public/svg/google-login.svg
  public/svg/kakao-login.svg
  public/svg/logo.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderDetailPage.tsx
  src/components/header/HeaderMypage.tsx
  src/components/header/HeaderSign.tsx
  src/components/mypage/BookmarkFeed.tsx
  src/components/mypage/DefaultProfile.tsx
  src/components/mypage/MyBookmark.tsx
  src/components/mypage/MyBookmarkIcon.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/MyPageTitle.tsx
  src/components/mypage/MyPlan.tsx
  src/components/mypage/MyPlanIcon.tsx
  src/components/mypage/MyReview.tsx
  src/components/mypage/MyReviewIcon.tsx
  src/components/mypage/ReviewFeed.tsx
  src/components/onboarding/OnBoardingButton.tsx
  src/components/onboarding/OnBoardingContentBox.tsx
  src/components/onboarding/OnBoardingSideButton.tsx
  src/components/sign/SignBox.tsx
  src/components/sign/SignButton.tsx
  src/components/sign/SignInput.tsx
  src/components/sign/SignSns.tsx
  src/layout/detailpage/layout.tsx
  src/layout/mypage/layout.tsx
  src/layout/onboarding/layout.tsx
  src/layout/signin/layout.tsx
  src/layout/signup/layout.tsx
  src/lib/store/useTabTitleStore.ts
  src/pages/detailpage/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: 💻Markup, 💻Style, 💻TypeScript

#12 Design/TripEdit : TripEdit Page 마크업 및 스타일링
  src/_document.tsx
  src/components/header/HeaderTripEdit.tsx
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripedit/MapPin.tsx
  src/components/tripedit/SaveButton.tsx
  src/components/tripedit/TripDays.tsx
  src/components/tripedit/TripEditMap.tsx
  src/layout/tripedit/layout.tsx
  src/lib/utils/getTripDay.ts
  src/pages/tripedit/index.tsx
  tailwind.config.ts
Labels: 💻Markup, 💻Style, 💻TypeScript

#21 Feature/signinpage
  package.json
  pnpm-lock.yaml
  public/svg/planeIcon.svg
  src/components/header/HeaderMain.tsx
  src/components/main/BestTravels.tsx
  src/components/main/MakePlan.tsx
  src/components/main/RecommandRegion.tsx
  src/components/sign/SignSns.tsx
  src/layout/main/layout.tsx
  src/lib/supabase/supabase.ts
  src/pages/main/index.tsx
  src/pages/search/index.tsx
Labels: 📑Docs, ✅Feat, 💻Next, 🪄Test, 💻Markup, 💻Style, 💻TypeScript, 🪪API

#22 Feat/TripReview : 카카오맵 API 활용하여 지도 기능 구현
  src/components/tripedit/TripEditMap.tsx
  src/components/tripreview/TripReviewFeed.tsx
  src/components/tripreviewdetail/TripDetailMap.tsx
  src/pages/tripreview/index.tsx
  src/pages/tripreviewdetail/index.tsx
Labels: ✅Feat, 💻Next, 💻TypeScript, 🪪API

#23 Feat/TripRegion:
  src/components/header/HeaderTripSelect.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/tripregion/RegionItem.tsx
  src/components/tripselect/ButtonLarge.tsx
  src/layout/tripregion/layout.tsx
  src/pages/tripregion/index.tsx
  src/store/RegionStore.ts
Labels: 🗝️Fix

#25 Feat/TripDays: 1차 기능구현 완료
  package.json
  pnpm-lock.yaml
  public/svg/calendar-inSelected.svg
  public/svg/calendar-selected.svg
  public/svg/plane-paper.svg
  src/components/tripdays/TripCalendar.tsx
  src/components/tripdays/TripDateInfo.tsx
  src/components/tripdays/TripScheduleInfo.tsx
  src/layout/tripdays/layout.tsx
  src/pages/tripdays/index.tsx
  src/store/DaysStore.ts
  src/styles/calendar.css
  src/utils/getTripDay.ts
Labels: ✅Feat, 💻Next, 💻Style, 💻TypeScript

#36 Feat : TripEdit 페이지 키워드 기반 마커 출력
  src/components/tripedit/TripDays.tsx
  src/components/tripedit/TripEditMap.tsx
  src/pages/tripedit/index.tsx
  src/store/useTripPlaceStore.ts
  src/utils/debounce.ts
  src/utils/getStaticPaths.ts
Labels: ✅Feat, 💻Next, 💻TypeScript, 🪪API, 🐻Zustand

#37 Feat/TripRegion: 토글 로직 수정
  public/svg/closeIcon.svg
  public/svg/userIcon.svg
  src/components/common/TripRegionDaysEdit.tsx
  src/components/header/BackButton.tsx
  src/components/header/CloseButton.tsx
  src/components/header/HeaderTripSelect.tsx
  src/components/header/HomeButton.tsx
  src/components/header/UserButton.tsx
  src/components/tripregion/RegionItem.tsx
  src/components/tripselect/TripTitle.tsx
  src/layout/tripregion/layout.tsx
  src/pages/tripregion/index.tsx
  src/store/RegionStore.ts
  src/store/RegionToggleStore.ts
Labels: 🚨Bug, ✅Feat, 🐻Zustand

#39 [Feat] EditProfile 페이지 프로필 수정 기능 구현
  src/components/header/HeaderEditProfile.tsx
  src/pages/editprofile/index.tsx
  src/pages/mypage/index.tsx
  src/store/useSessionStore.ts
  src/utils/uploadUserProfile.ts
Labels: ✅Feat, 💻Next, 💻TypeScript, 🪪API, 🐻Zustand

#41 [Feat] Supabse 데이터 통신 통한 사용자 프로필 렌더링
  src/components/header/HeaderMypage.tsx
  src/pages/editprofile/index.tsx
  src/pages/mypage/index.tsx
  src/store/useSessionStore.ts
Labels: ✅Feat, 💻Next, 💻TypeScript, 🪪API

#42 Feat/TripRegion: 마크업 완료 및 Store 수정
  src/components/tripregion/RegionItem.tsx
  src/components/tripregion/TourCategoryItem.tsx
  src/pages/tripregion/index.tsx
  src/store/DaysStore.ts
  src/store/RegionStore.ts
  src/store/RegionToggleStore.ts
Labels: 🚨Bug, 💻Markup, 🐻Zustand

#43 Feature/signinpage
  src/components/mypage/MyPageTab.tsx
  src/layout/signnickname/layout.tsx
  src/lib/supabase/Auth.ts
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signnickname/index.tsx
Labels: ✅Feat, 💻Next, 💻Markup, 💻Style, 💻TypeScript

#47 Feat/TripRegion:
  public/svg/search-inSearched.svg
  public/svg/search-searched.svg
  src/components/tripregion/RegionItem.tsx
  src/components/tripregion/TourCategoryItem.tsx
  src/components/tripselect/ButtonLarge.tsx
  src/components/tripselect/TripTitle.tsx
  src/layout/tripregion/layout.tsx
  src/lib/tour/tour.ts
  src/pages/tripregion/index.tsx
Labels: ✅Feat, 🗝️Fix, 💻Style, 💻TypeScript, 🪪API, 🌏Accessibility, 🐻Zustand
