Repository WeonTrip-WonT/WonT, pull requests merged in 2024-03, with the labels that each got.

#50 Feat/TripRegion 페이지 UI 버그 수정 및 검색 기능 구현
  src/components/tripregion/RegionItem.tsx
  src/layout/tripregion/layout.tsx
  src/pages/tripdays/index.tsx
  src/pages/tripregion/index.tsx
  src/utils/getTripDay.ts
Labels: ✅Feat, 🗝️Fix, 🌏Accessibility

#53 Feat : TripEditMap에 사용자 일정별 마커 및 루트 선 렌더링, 토글 기능 구현, 드래그앤드롭 기능 구현
  package.json
  pnpm-lock.yaml
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripedit/SaveButton.tsx
  src/components/tripedit/TripDays.tsx
  src/components/tripedit/TripEditMap.tsx
  src/pages/tripedit/index.tsx
  src/store/useTripPlaceStore.ts
  src/store/useViewPlanStore.ts
Labels: 🚨Bug, ✅Feat, 💻Next, 💻TypeScript, 🪪API, 🐻Zustand

#54 Feat/TripPlaceAccommodation: 지도 기능 구현
  src/components/tripaccommodation/TripAccommodationMap.tsx
  src/components/tripregion/RegionItem.tsx
  src/lib/tour/tour.ts
  src/pages/tripaccommodation/index.tsx
  src/pages/tripregion/index.tsx
  src/store/RegionStore.ts
Labels: ✅Feat, 💻TypeScript, 🪪API

#56 Feat/trip place accommodation
  next.config.mjs
  src/components/common/DefaultImage.tsx
  src/components/tripaccommodation/TripAccommodationMap.tsx
  src/components/tripselect/LocalItem.tsx
  src/components/tripselect/SelectDaysInfo.tsx
  src/components/tripselect/SelectItem.tsx
  src/layout/tripaccommodation/layout.tsx
  src/lib/tour/tour.ts
  src/pages/tripaccommodation/index.tsx
  src/pages/tripedit/index.tsx
  src/store/AccommodationStore.ts
  src/types/DataProps.ts
Labels: ✅Feat, 💻Style, 💻TypeScript, 🪪API, 🐻Zustand, 🗺️Map

#58 Feat/TripPlaceAccommodation: (여행 관광 장소 선택 페이지) 기능 구현 1차 완료
  src/components/common/DefaultImage.tsx
  src/components/tripaccommodation/LocalAccommodationItem.tsx
  src/components/tripaccommodation/TripAccommodationsMap.tsx
  src/components/tripplace/LocalPlaceItem.tsx
  src/components/tripplace/TripPlaceMap.tsx
  src/components/tripplace/TripPlacesMap.tsx
  src/components/tripselect/SelectDaysInfo.tsx
  src/layout/tripaccommodation/layout.tsx
  src/layout/tripplace/layout.tsx
  src/lib/tour/tour.ts
  src/pages/tripaccommodation/index.tsx
  src/pages/tripplace/index.tsx
  src/store/AccommodationStore.ts
  src/store/AccommodationsStore.ts
  src/store/PlacesStore.ts
Labels: ✅Feat, 🪪API, 🐻Zustand, 🗺️Map

#60 Feat/TripDate: 여행 기간 선택 Storage 모든 날짜 저장 로직 구현
  src/components/common/TripRegionDaysEdit.tsx
  src/components/tripdate/TripCalendar.tsx
  src/components/tripdate/TripDateInfo.tsx
  src/components/tripdate/TripScheduleInfo.tsx
  src/layout/tripdate/layout.tsx
  src/pages/tripdate/index.tsx
  src/pages/tripedit/index.tsx
  src/store/DatesStore.ts
  src/utils/getTripDate.ts
Labels: ✅Feat, 💻TypeScript, 🐻Zustand

#61 Rename: TripDays => TripDate 페이지 이름 변경
  src/components/tripdays/TripCalendar.tsx
  src/components/tripdays/TripDateInfo.tsx
  src/components/tripdays/TripScheduleInfo.tsx
  src/components/tripselect/SelectDateInfo.tsx
  src/layout/tripdays/layout.tsx
  src/pages/tripaccommodation/index.tsx
  src/pages/tripdate/index.tsx
  src/pages/tripdays/index.tsx
  src/pages/tripplace/index.tsx
  src/pages/tripregion/index.tsx
  src/store/DaysStore.ts
Labels: 🚨Bug, 🗝️Fix

#69 Feat : SupaBase에 등록한 유저 일정 데이터 렌더링, TourAPI 이미지 렌더링
  src/components/mypage/MyPlan.tsx
  src/pages/editprofile/index.tsx
  src/pages/mypage/index.tsx
  src/types/PlanDataTypes.ts
Labels: ✅Feat, 🗝️Fix, 💻TypeScript, 🪪API, 🐻Zustand

#68 Feat / Fix : Accommondation, Place 데이터를 통한 일정 구현 및 SupaBase 일정 등록 기능 구현
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripedit/AddSchedule.tsx
  src/components/tripedit/SaveButton.tsx
  src/components/tripedit/TripDays.tsx
  src/components/tripedit/TripEditMap.tsx
  src/pages/editprofile/index.tsx
  src/pages/tripedit/index.tsx
  src/store/AccommodationsStore.ts
  src/store/DatesStore.ts
  src/store/PlacesStore.ts
  src/store/SelectedPlanStore.ts
Labels: 🚨Bug, ✅Feat, 💻Next, 🗝️Fix, 💻TypeScript, 🪪API, 🐻Zustand, 🗺️Map

#71 Design/MyPlanDetail: "서비스 준비중" 페이지 스타일링
  src/layout/myplan/layout.tsx
  src/pages/myplan/[myplanId].tsx
Labels: ⚙Sync, 💻Next, 💻Markup

#73 Feat/TripPlace_Accommodation: 선택한 숙소, 관광 장소 Storage 타입 변경 (Object -> Array)
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripedit/TripDays.tsx
  src/components/tripedit/TripEditMap.tsx
  src/pages/tripaccommodation/index.tsx
  src/pages/tripedit/index.tsx
  src/pages/tripplace/index.tsx
  src/store/AccommodationsStore.ts
  src/store/PlacesStore.ts
  src/types/DataProps.ts
  src/utils/setTripRange.ts
Labels: 💻TypeScript, 🐻Zustand

#74 [Fix / Feat] 일정 데이터 수정 및 로직 수정 진행중, 추가 버튼 클릭 시 해당 index path로 넘겨줌
  src/components/tripedit/AddSchedule.tsx
  src/components/tripedit/TripDays.tsx
  src/pages/tripplace/index.tsx
  src/types/DataProps.ts
Labels: 🚨Bug, 💻Next, 🗝️Fix, 💻TypeScript, 🐻Zustand

#75 Feat/TripPlace_Accommodation
  src/components/common/DefaultImage.tsx
  src/components/common/SelectDateInfo.tsx
  src/components/tripaccommodation/LocalAccommodationItem.tsx
  src/components/tripaccommodation/TripAccommodationsMap.tsx
  src/components/tripplace/LocalPlaceItem.tsx
  src/pages/tripaccommodation/[tripdate].tsx
  src/pages/tripplace/[tripdate].tsx
  src/store/AccommodationsStore.ts
  src/store/PlacesStore.ts
Labels: ✅Feat, 💻Next, 🗝️Fix, 💻TypeScript, 🐻Zustand

#77 Fix: 숙소 / (관광) 장소 선택할 때, 해당 날짜에만 저장되도록 수정
  src/store/AccommodationsStore.ts
  src/store/PlacesStore.ts
Labels: 🗝️Fix, 🐻Zustand

#82 Feat : 유저 리뷰 등록 및 렌더링
  package.json
  pnpm-lock.yaml
  src/components/mypage/MyPlan.tsx
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripreview/TripReviewFeed.tsx
  src/layout/tripreviewwriting/layout.tsx
  src/pages/tripreview/index.tsx
  src/pages/tripreviewwriting/index.tsx
  src/store/useReviewStore.ts
  src/types/ReviewDataTypes.ts
  src/utils/uploadReviewImage.ts
Labels: ✅Feat, 💻Next, 💻TypeScript, 🪪API, 🐻Zustand

#83 Feat: TripRegion 페이지 - regionCode별 지역 이미지 로딩
  src/components/tripregion/RegionItem.tsx
  src/pages/tripregion/index.tsx
Labels: ✅Feat

#86 Feat : TripEdit Header Router 설정 및 지도 Marker 설정
  package.json
  pnpm-lock.yaml
  src/app/loading.tsx
  src/asset/loading/LoadingSpinner.tsx
  src/asset/loading/loading.json
  src/components/header/HeaderTripEdit.tsx
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripedit/TripEditMap.tsx
  src/pages/tripedit/index.tsx
  src/pages/tripreview/index.tsx
  src/pages/tripreviewdetail/index.tsx
Labels: ✅Feat, 💻Next, 🪪API, 🗺️Map

#87 Fix : EditProfile 오류 해결
  src/pages/editprofile/index.tsx
Labels: 🚨Bug, ✅Feat, 🗝️Fix, 🪪API

#88 Feat: 에러 페이지 - 레이아웃 스타일링
  src/app/error.tsx
  src/pages/404.tsx
  src/pages/_error.tsx
Labels: 🚨Bug, 💻Next, 💻Markup

#90 Feat/TripRegion
  src/components/tripregion/RegionItem.tsx
  src/pages/tripregion/index.tsx
  src/store/RegionStore.ts
Labels: ✅Feat, 💻Style, 🪪API

#92 Feat : MyPage 일정 렌더링 및 여행 리뷰 등록, 상세페이지 렌더링
  public/detailpage/detailPlaceDefault.jpg
  src/components/header/HeaderMypage.tsx
  src/components/header/HeaderTripEdit.tsx
  src/components/header/HeaderTripReview.tsx
  src/components/main/BestTravels.tsx
  src/components/mypage/MyBookmark.tsx
  src/components/mypage/MyPageTitle.tsx
  src/components/mypage/MyPlan.tsx
  src/components/mypage/MyReview.tsx
  src/components/mypage/ReviewFeed.tsx
  src/components/tripedit/AddPlanButton.tsx
  src/components/tripreview/TripReviewFeed.tsx
  src/components/tripreviewdetail/DetailPlace.tsx
  src/components/tripreviewdetail/DetailReviewFeed.tsx
  src/components/tripreviewwriting/ModalTripDate.tsx
  src/components/tripreviewwriting/ModalTripRegion.tsx
  src/components/tripreviewwriting/SelectButton.tsx
  src/components/tripreviewwriting/TripRegionItem.tsx
  src/lib/functionprogress/functionProgress.json
  src/pages/tripedit/[tripedit].tsx
  src/pages/tripedit/index.tsx
  src/pages/tripreview/index.tsx
  src/pages/tripreviewdetail/[userReviewId].tsx
  src/pages/tripreviewdetail/index.tsx
  src/pages/tripreviewwriting/index.tsx
  src/store/useModalStateStore.ts
  src/store/useReviewStore.ts
  src/store/useWriterStore.ts
  src/types/ReviewDataTypes.ts
  src/utils/FunctionProgress.tsx
  src/utils/getDDay.ts
Labels: ✅Feat, 💻Next, 💻TypeScript, 🪪API, 🐻Zustand
